# Chapter 2 넘파이 및 판다스 기초 테스트

## 넘파이 문제

### 1. np.arange() 함수를 이용해서 다음 배열을 만들어보시오.
array1 = [-3 -2 -1 0 1 2 3]

In [12]:
import numpy as np
%precision 3

array1 = np.arange(-3,4)
print(array1)

[-3 -2 -1  0  1  2  3]


### 2. arange()와 reshape()를 사용해서 다음 행렬을 만들어보시오.
[[ 1  2  3  4  5]
 
 [ 6  7  8  9 10]
 
 [11 12 13 14 15]
 
 [16 17 18 19 20]
 
 [21 22 23 24 25]]

In [13]:
array2 = np.arange(1,26)
array2 = array2.reshape(5,5)
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### 3. 난수 5개를 생성해 배열(array)에 저장하고, 큰 것부터 작은 순으로 정렬하시오.

In [15]:
import numpy.random as random
rnd_array = np.array(random.rand(5))
rnd_array[::-1].sort()
print(rnd_array)

[0.995 0.645 0.457 0.408 0.266]


## 판다스 문제

In [16]:
# 아래 코드를 먼저 실행해서 표를 확인하고 문제 4~6을 풀어보세요.
import pandas as pd
from pandas import Series,DataFrame


attri_data1 = {'ID':['1','2','3','4','5'],
               'Sex':['F','F','M','M','F'],
               'Money':[1000,2000,500,300,700],
               'Name':['Suji','Minji','Taeho','Jinsung','Suyoung']}

attri_data_frame1 = DataFrame(attri_data1)
attri_data_frame1

ID Sex  Money     Name
0  1   F   1000     Suji
1  2   F   2000    Minji
2  3   M    500    Taeho
3  4   M    300  Jinsung
4  5   F    700  Suyoung

### 4. Money가 500 이상인 사람만 추려내 표시하세요.

In [17]:
attri_data_frame1[attri_data_frame1['Money'] >= 500]

ID Sex  Money     Name
0  1   F   1000     Suji
1  2   F   2000    Minji
2  3   M    500    Taeho
4  5   F    700  Suyoung

### 5. 성별 평균 Money를 구하세요.

In [18]:
attri_data_frame1.groupby("Sex")["Money"].mean()

Sex
F    1233.333333
M     400.000000
Name: Money, dtype: float64

### 6. 위 데이터와 아래의 데이터를 결합하고, 이후 Money, Math, English의 평균을 구하세요.

In [19]:
attri_data2 = {
        'ID':['3','4','7']
        ,'Math':[60,30,40]
        ,'English':[80,20,30]
}
attri_data_frame2 = DataFrame(attri_data2)
attri_data_frame2

ID  Math  English
0  3    60       80
1  4    30       20
2  7    40       30

In [11]:
# 여기에 풀이코드를 쓰고 실행하세요.
merge_data = attri_data_frame1.merge(attri_data_frame2)
merge_data.mean()

ID          17.0
Money      400.0
Math        45.0
English     50.0
dtype: float64